<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Group 6 Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Group_06_Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_06_Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Group_06_Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Group_06_Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_06_Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_06_Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_06_Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_06_Analysis_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_06_Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_06_Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_06_Analysis_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group 6 Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1 Introduction</h1>
<p>Online movie rating platforms such as IMDB provide valuable insights into audience opinions by collecting user ratings and reviews, which many viewers rely on when choosing what movies to watch (Topal &amp; Ozsoyoglu, 2016).</p>
<p>This analysis aims to investigate which properties of films influence whether they are rated by IMDB as greater than 7 or not. In particular, this analysis examines how factors such as the film’s release year, duration, production budget, number of viewer votes and genre are associated with the probability of receiving a high rating.</p>
<p>To investigate this problem, our group first conducted exploratory data analysis to identify potential associations between the variables, and then used a Generalised Linear Model(GLM). Since the response variable indicates whether a film is rated above 7, our group used a binary logistic regression model for the analysis.</p>
</section>
<section id="data-description" class="level1">
<h1>2 Data Description</h1>
<p>The dataset used in this project is dataset06.csv. The dataset contains information of films from the IMDB database and each observation in the dataset represents a single film.</p>
<p>The dataset includes several variables describing film characteristics, including the year of release, film duration, production budget, number of viewer votes and film genre. In addition, the dataset includes the IMDb rating for each film.</p>
<p>Using these variables, our group can investigate the possible correlation between various film attributes and the probability of receiving a rating of 7 or higher.</p>
<p>•film.id – The unique identifier for the film</p>
<p>•year – Year of release of the film in cinemas</p>
<p>•length – Duration (in minutes)</p>
<p>•budget – Budget for the films production (in $1000000s)</p>
<p>•votes – Number of positive votes received by viewers</p>
<p>•genre – Genre of the film</p>
<p>•rating – IMDB rating from 0-10</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dataset06.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  film_id year length budget votes       genre rating
1   31804 2002     18    9.6    15       Drama    8.0
2   25453 2000     98   13.8    23      Action    3.3
3    5479 1989     81   11.5    57 Documentary    7.9
4   44235 1995    100    7.5    32      Action    3.4
5   14580 2003     80   10.8    30      Action    2.6
6   31060 1990     90   13.8    81      Comedy    3.5</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1937 obs. of  7 variables:
 $ film_id: int  31804 25453 5479 44235 14580 31060 44255 22834 58656 23126 ...
 $ year   : int  2002 2000 1989 1995 2003 1990 1967 1987 1968 1931 ...
 $ length : int  18 98 81 100 80 90 98 58 174 3 ...
 $ budget : num  9.6 13.8 11.5 7.5 10.8 13.8 13.6 15.6 11.3 15.7 ...
 $ votes  : int  15 23 57 32 30 81 19 24 89 7 ...
 $ genre  : chr  "Drama" "Action" "Documentary" "Action" ...
 $ rating : num  8 3.3 7.9 3.4 2.6 3.5 8.2 8.6 4.4 7.9 ...</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    film_id           year          length           budget     
 Min.   :    5   Min.   :1896   Min.   :  1.00   Min.   : 3.20  
 1st Qu.:14508   1st Qu.:1958   1st Qu.: 76.00   1st Qu.:10.10  
 Median :29170   Median :1982   Median : 90.00   Median :12.00  
 Mean   :29257   Mean   :1976   Mean   : 82.83   Mean   :12.03  
 3rd Qu.:44016   3rd Qu.:1997   3rd Qu.:100.00   3rd Qu.:14.00  
 Max.   :58781   Max.   :2005   Max.   :316.00   Max.   :21.20  
                                NA's   :103                     
     votes             genre               rating     
 Min.   :     5.0   Length:1937        Min.   :0.600  
 1st Qu.:    12.0   Class :character   1st Qu.:3.700  
 Median :    31.0   Mode  :character   Median :4.600  
 Mean   :   590.5                      Mean   :5.294  
 3rd Qu.:   116.0                      3rd Qu.:7.700  
 Max.   :103854.0                      Max.   :9.300  
                                                      </code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level1">
<h1>3 Data Cleaning</h1>
<p>Before conducting the analysis, several data cleaning steps were performed to prepare the dataset for modelling.</p>
<p>First, observations containing missing values were removed using <code>na.omit()</code> to ensure that incomplete records did not affect the analysis.</p>
<p>Next, a binary response variable <code>high_rating</code> was created from the original rating variable. Films with ratings greater than 7 were coded as 1, while films with ratings of 7 or below were coded as 0.</p>
<p>Finally, the number of votes was log-transformed to reduce skewness and improve the interpretability of the variable.</p>
<p>The cleaned dataset was stored as <code>df</code> in this script and used in all subsequent analysis and modelling steps.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dataset06.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remove missing values</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(df)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create binary response variable</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>high_rating <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>rating <span class="sc">&gt;</span> <span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># log transform votes</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>log_votes <span class="ot">&lt;-</span> <span class="fu">log</span>(df<span class="sc">$</span>votes)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>genre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Action   Animation      Comedy Documentary       Drama     Romance 
        546         109         432          91         562          18 
      Short 
         76 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>high_rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
1228  606 </code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>4 Exploratory Data Analysis</h1>
<p>To explore the relationships between film characteristics and the likelihood of receiving a rating greater than 7, several exploratory visualisations were produced using the cleaned dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># create bar plot showing proportion of high-rated films by genre</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">fill =</span> <span class="fu">factor</span>(high_rating))) <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Proportion of High Rating by Genre"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Genre"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Rating &gt; 7"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-genre" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_06_Analysis_files/figure-html/fig-genre-1.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Proportion of films rated above 7 across different genres.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-genre" class="quarto-xref">Figure&nbsp;1</a>, the proportion of films with ratings above and below 7 vary across different genres.</p>
<p>Short films and documentaries have the highest proportions of high-rated films, followed by animation and comedy. In contrast, drama and romance show very low proportions of films rated above 7. Action films also show a relatively low proportion of high-rated films.</p>
<p>This suggests that genre may be associated with the likelihood of a film receiving a high IMDB rating.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># create histogram to compare distribution of log-transformed votes</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> log_votes, <span class="at">fill =</span> <span class="fu">factor</span>(high_rating))) <span class="sc">+</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Log(Votes) by Rating Group"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"log(Votes)"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Rating &gt; 7"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-votes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-votes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_06_Analysis_files/figure-html/fig-votes-1.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-votes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of log-transformed votes by rating group.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-votes" class="quarto-xref">Figure&nbsp;2</a> shows the distribution of the log-transformed number of votes for films with rating over and below 7.</p>
<p>For both groups, most films fall within the lower ranges of log(votes), indicating that regardless of their ratings, only a small number of films received a very high number of votes, most films received a moderate number of votes.</p>
<p>Although the red bars (ratings ≤ 7) are consistently higher than the blue bars (ratings &gt; 7), this does not mean that lower-rated films are more likely to receive more votes.</p>
<p>First, films rated above 7 appear to account for a smaller share of the overall dataset. So the taller red bars are results of the difference in total group sizes.</p>
<p>Second, the distributions of the two groups overlap substantially, both extending from approximately log(Votes) ≈ 2 to over 10. This suggests that the number of votes does not strongly distinguish between high-rated and low-rated films.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># create boxplot to compare film length across rating groups</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(high_rating), <span class="at">y =</span> length, <span class="at">fill =</span> <span class="fu">factor</span>(high_rating))) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"Rating ≤ 7"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Rating &gt; 7"</span>)) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Film Length by Rating Group"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rating Group"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Length (mins)"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-length" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_06_Analysis_files/figure-html/fig-length-1.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of film length across rating groups.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-length" class="quarto-xref">Figure&nbsp;3</a>, the distribution of film length differs slightly between films with ratings above 7 and those with ratings of 7 or below.</p>
<p>The median film length of lower-rated films appears slightly higher than the highly rated films.</p>
<p>In addition, the distribution of film length among highly rated films appears more variable, with a wider spread of values.</p>
<p>Several longer films are also observed among the lower-rated group as outliers.</p>
<p>While the exploratory analysis focused on selected key variables such as genre, film length, and log-transformed votes, other variables including year and budget were not visualised due to space constraints. However, these variables were still included in the regression model as they are theoretically relevant and may contribute to explaining variation in film ratings.</p>
<p>Overall, the boxplot suggests that film length may be associated with rating, although the relationship does not appear to be very strong.</p>
</section>
<section id="model-glm" class="level1">
<h1>5 Model (GLM)</h1>
<p>To examine how film properties influence the probability of receiving a rating above 7, a logistic regression model was fitted. Since the response variable high_rating is binary, a GLM with a binomial family and logit link was used.</p>
<section id="model-specification" class="level2">
<h2 class="anchored" data-anchor-id="model-specification">5.1 Model specification</h2>
<p>Since the response variable <code>high_rating</code> is binary, a logistic regression model is used. Let <span class="math inline">\(p_i\)</span> denote the probability that film <span class="math inline">\(i\)</span> receives a rating above 7.</p>
<p>The model assumes</p>
<p><span class="math display">\[
Y_i \sim \text{Binomial}(1, p_i)
\]</span></p>
<p>and uses the logit link function as Model 1.</p>
<p>Model 1 includes the predictors: year, length, log_votes, and budget.</p>
<p><span class="math display">\[
\log\left(\frac{p_i}{1-p_i}\right)
=
\beta_0
+
\beta_1 year_i
+
\beta_2 length_i
+
\beta_3 log\_votes_i
+
\beta_4 budget_i
\]</span></p>
<p>Model 2 additionally includes the categorical variable <code>genre</code>. <span class="math display">\[
\log\left(\frac{p_i}{1-p_i}\right)
=
\beta_0
+
\beta_1 \text{year}_i
+
\beta_2 \text{length}_i
+
\beta_3 \text{log\_votes}_i
+
\beta_4 \text{budget}_i
+
\sum_{j} \gamma_j \text{genre}_{ij}
\]</span></p>
<p>where <span class="math inline">\(\text{genre}_{ij}\)</span> represents dummy variables for each genre category, and one category (Action) is used as the reference group.</p>
<p>In this model, the inclusion of genre allows for differences in the probability of receiving a high rating across film types. Each genre coefficient represents the change in log-odds relative to the reference category, holding other variables constant.</p>
</section>
<section id="model-fitting" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting">5.2 Model fitting</h2>
<p>The two models were fitted in R as follows.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  high_rating <span class="sc">~</span> year <span class="sc">+</span> length <span class="sc">+</span> log_votes <span class="sc">+</span> budget,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  high_rating <span class="sc">~</span> year <span class="sc">+</span> length <span class="sc">+</span> log_votes <span class="sc">+</span> budget <span class="sc">+</span> genre,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">5.3 Model comparison</h2>
<p>The two models were compared using the Akaike Information Criterion (AIC).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute AIC values for both models</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>aic_table <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model1, model2)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># display results as a formatted table</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(aic_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-aic" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-aic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Comparison of AIC values for Model 1 and Model 2.
</figcaption>
<div aria-describedby="tbl-aic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">model1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1594.8069</td>
</tr>
<tr class="even">
<td style="text-align: left;">model2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">969.9133</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-aic" class="quarto-xref">Table&nbsp;1</a>, Model 2 provides a better fit.</p>
<p>Model 2 has a considerably lower AIC than Model 1, suggesting that the inclusion of <code>genre</code> improves the fit of the model.</p>
</section>
<section id="selected-model" class="level2">
<h2 class="anchored" data-anchor-id="selected-model">5.4 Selected model</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = high_rating ~ year + length + log_votes + budget + 
    genre, family = binomial(link = "logit"), data = df)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-3.0313  -0.3432  -0.1129   0.1618   3.9135  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -22.774970   7.542368  -3.020  0.00253 ** 
year               0.010055   0.003838   2.620  0.00879 ** 
length            -0.065026   0.004820 -13.492  &lt; 2e-16 ***
log_votes          0.009788   0.051965   0.188  0.85060    
budget             0.503195   0.036815  13.668  &lt; 2e-16 ***
genreAnimation    -0.489039   0.434795  -1.125  0.26069    
genreComedy        3.119344   0.223678  13.946  &lt; 2e-16 ***
genreDocumentary   5.243089   0.495149  10.589  &lt; 2e-16 ***
genreDrama        -1.642342   0.292199  -5.621  1.9e-08 ***
genreRomance      -1.943741   1.807731  -1.075  0.28227    
genreShort         3.501378   1.080476   3.241  0.00119 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2327.27  on 1833  degrees of freedom
Residual deviance:  947.91  on 1823  degrees of freedom
AIC: 969.91

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>To further assess the models, the deviance values were also examined. The null deviance for Model 2 was 2327.27, while the residual deviance was reduced to 947.91. This substantial reduction indicates that the predictors included in the model explain a considerable amount of variation in whether a film receives a rating above 7.</p>
<p>Based on the AIC comparison between 2 models and the reduction in deviance by Model 2, Model 2 was selected as the final model for interpretation. Model 2 provides a better representation of the factors associated with high IMDB ratings and is therefore used in the Results section.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> predicted_prob, <span class="at">fill =</span> <span class="fu">factor</span>(high_rating))) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Model 2: Distribution of Predicted Probabilities"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predicted Probability (Rating &gt; 7)"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Actual Rating &gt; 7"</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"lightcoral"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"No (Rating ≤ 7)"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Yes (Rating &gt; 7)"</span>)) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-model2prob" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model2prob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_06_Analysis_files/figure-html/fig-model2prob-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model2prob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Distribution of Predicted Probabilities of Model 2
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-model2prob" class="quarto-xref">Figure&nbsp;4</a>, there is almost no overlap between the two classes, indicating that the model 2 has strong discriminative power, delivers stable and reliable predictions, and is an excellent classification model.</p>
</section>
</section>
<section id="finding" class="level1">
<h1>6 Finding</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract coefficient estimates from model summary</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>coef_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(model2)<span class="sc">$</span>coefficients</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># display coefficient table</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(coef_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-model2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Coefficient estimates for the final logistic regression model.
</figcaption>
<div aria-describedby="tbl-model2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-22.7749704</td>
<td style="text-align: right;">7.5423683</td>
<td style="text-align: right;">-3.0196046</td>
<td style="text-align: right;">0.0025310</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0.0100553</td>
<td style="text-align: right;">0.0038376</td>
<td style="text-align: right;">2.6201897</td>
<td style="text-align: right;">0.0087881</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">-0.0650261</td>
<td style="text-align: right;">0.0048197</td>
<td style="text-align: right;">-13.4917972</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_votes</td>
<td style="text-align: right;">0.0097877</td>
<td style="text-align: right;">0.0519654</td>
<td style="text-align: right;">0.1883511</td>
<td style="text-align: right;">0.8506014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">0.5031948</td>
<td style="text-align: right;">0.0368151</td>
<td style="text-align: right;">13.6681601</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreAnimation</td>
<td style="text-align: right;">-0.4890389</td>
<td style="text-align: right;">0.4347951</td>
<td style="text-align: right;">-1.1247573</td>
<td style="text-align: right;">0.2606919</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreComedy</td>
<td style="text-align: right;">3.1193441</td>
<td style="text-align: right;">0.2236778</td>
<td style="text-align: right;">13.9457054</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreDocumentary</td>
<td style="text-align: right;">5.2430893</td>
<td style="text-align: right;">0.4951489</td>
<td style="text-align: right;">10.5889142</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreDrama</td>
<td style="text-align: right;">-1.6423418</td>
<td style="text-align: right;">0.2921991</td>
<td style="text-align: right;">-5.6206251</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreRomance</td>
<td style="text-align: right;">-1.9437411</td>
<td style="text-align: right;">1.8077313</td>
<td style="text-align: right;">-1.0752378</td>
<td style="text-align: right;">0.2822683</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreShort</td>
<td style="text-align: right;">3.5013784</td>
<td style="text-align: right;">1.0804758</td>
<td style="text-align: right;">3.2405894</td>
<td style="text-align: right;">0.0011928</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>According to <a href="#tbl-model2" class="quarto-xref">Table&nbsp;2</a>, several predictors are statistically significant.</p>
<p>Model 2, which includes <code>genre</code> as an additional predictor, provides a substantially better fit than Model 1, with a much lower AIC (969.91 compared with 1594.81). This indicates that genre plays an important role in explaining whether a film receives an IMDB rating above 7.</p>
<p>From the fitted logistic regression model, several predictors are statistically significant.</p>
<p>The coefficient for <code>year</code> is positive and statistically significant (p = 0.00879), suggesting that more recently released films are slightly more likely to receive a rating above 7, holding other variables constant.</p>
<p>The coefficient for <code>length</code> is negative and highly statistically significant (p &lt; 0.001), indicating that longer films are less likely to receive a high rating.</p>
<p>The coefficient for <code>budget</code> is positive and highly statistically significant (p &lt; 0.001), implying that films with larger production budgets are more likely to achieve ratings above 7.</p>
<p>In contrast, <code>log_votes</code> is not statistically significant (p = 0.8506), indicating that after controlling for the other variables, the number of votes does not meaningfully affect the probability of a high rating.</p>
<p>For the categorical variable <code>genre</code>, Action is the reference category. Relative to Action films, Comedy, Documentary, and Short films have significantly higher odds of receiving a rating above 7 (all p &lt; 0.01), while Drama films have significantly lower odds (p &lt; 0.001). Animation and Romance are not significantly different from Action films at the 5% significance level.</p>
<p>Overall, the results show that <code>genre</code>, <code>budget</code>, <code>length</code>, and <code>year</code> are important determinants of high IMDB ratings, while <code>log_votes</code> is not significant in the presence of the other variables.</p>
</section>
<section id="discussion" class="level1">
<h1>7 Discussion</h1>
<p>This study investigated which film characteristics influence whether a film receives an IMDB rating above 7 using a logistic regression model.</p>
<p>The results demonstrate that <code>genre</code> is one of the most important factors. Films such as Documentary, Comedy, and Short are significantly more likely to receive high ratings compared to Action films, while Drama films are less likely to achieve high ratings. This suggests that audience preferences and evaluation standards vary across genres.</p>
<p>The analysis also shows that <code>budget</code> has a strong positive effect, indicating that higher-budget films are more likely to receive high ratings. This may be because larger budgets allow for better production quality, stronger marketing, and wider distribution.</p>
<p>In addition, <code>length</code> has a negative effect, suggesting that longer films are less likely to receive ratings above 7. This may indicate that shorter films are more engaging or easier for audiences to evaluate positively.</p>
<p>Although the number of votes might be expected to reflect popularity, <code>log_votes</code> is not statistically significant in the model. This suggests that the number of votes alone does not determine whether a film receives a high rating once other factors are taken into account.</p>
<p>The effect of <code>year</code> is positive but relatively small, indicating that more recent films are slightly more likely to receive higher ratings.</p>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">7.1 Limitations</h2>
<p>There are several limitations to this analysis. First, the dataset does not include potentially important variables such as director, cast, awards, or marketing, which may influence film ratings. Second, the model assumes linear relationships between predictors and the log-odds of a high rating, which may oversimplify real-world relationships. Finally, this analysis is based on observational data and cannot establish causal relationships.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">7.2 Conclusion</h2>
<p>In conclusion, this analysis shows that <code>genre</code>, <code>budget</code>, <code>length</code>, and <code>year</code> significantly influence whether a film receives an IMDB rating above 7. Among these, genre appears to be the most important factor. These findings provide useful insights for understanding the characteristics associated with highly rated films.</p>
</section>
</section>
<section id="references" class="level1">
<h1>8 References</h1>
<ul>
<li>K. Topal and G. Ozsoyoglu, “Movie review analysis: Emotion analysis of IMDb movie reviews,” 2016 IEEE/ACM International Conference on Advances in Social Networks Analysis and Mining (ASONAM), San Francisco, CA, USA, 2016, pp.&nbsp;1170-1176, doi: 10.1109/ASONAM.2016.7752387.</li>
</ul>
</section>
<section id="section" class="level1">
<h1></h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>